# Generated by Django 5.2.7 on 2025-10-30 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pet_photos/')),
                ('species', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('breed', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('microchip_id', models.CharField(blank=True, max_length=50, null=True)),
                ('weight_kg', models.FloatField()),
                ('speyed_neutered', models.BooleanField(default=False)),
                ('vaccination_status', models.CharField(choices=[('up_to_date', 'Up to date'), ('due_soon', 'Due soon'), ('overdue', 'Overdue'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_vaccination_date', models.DateField(blank=True, null=True)),
                ('vet_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vet_contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vet_address_1', models.TextField(blank=True, null=True)),
                ('vet_address_2', models.TextField(blank=True, null=True)),
                ('vet_city', models.CharField(blank=True, max_length=100, null=True)),
                ('vet_state', models.CharField(blank=True, max_length=100, null=True)),
                ('vet_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('vet_country', models.CharField(blank=True, max_length=100, null=True)),
                ('last_known_location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
