# Generated by Django 5.2.7 on 2025-10-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_lost',
            field=models.BooleanField(default=False),
        ),
    ]
