# Generated by Django 5.2.7 on 2025-10-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_guid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='guid',
            new_name='user_id',
        ),
    ]
